### ISSUE TITLE
Feature request - allow listening port to be changed using environment

### ISSUE THREAD

**Issue by MattCarothers** [opendistro-for-elasticsearch/performance-analyzer#52]
We run multiple ES nodes on a single physical machine using --network host.  Only one of the nodes can bind to port 9600 at a time, so we need an easy way to change the listening port in our docker-compose file.  It would be nice if we could do something like this:
```
services:
  es00:
    image: amazon/opendistro-for-elasticsearch:0.8.0
    container_name: es00
    environment:
      - http.port=9200
      - node.data=true
      - node.master=false
      - plugin.performance-analyzer.webservice-listener-port=9600
    network_mode: host
  es01:
    image: amazon/opendistro-for-elasticsearch:0.8.0
    container_name: es01
    environment:
      - http.port=9201
      - node.data=true
      - node.master=false
      - plugin.performance-analyzer.webservice-listener-port=9601
    network_mode: host
```
